
project_id = "ymygyagbvbsdfkduxmgu"

[functions.codechat-webhook]
verify_jwt = false

[functions.codechat-v2-webhook]
verify_jwt = false

[functions.yumer-unified-webhook]
verify_jwt = false

[functions.whatsapp-decrypt-audio]
verify_jwt = false

[functions.speech-to-text]
verify_jwt = false
