
project_id = "ymygyagbvbsdfkduxmgu"

[functions.codechat-webhook]
verify_jwt = false

[functions.codechat-v2-webhook]
verify_jwt = false

[functions.yumer-unified-webhook]
verify_jwt = false

[functions.batch-scheduler]
verify_jwt = false

[functions.process-message-batches]
verify_jwt = false

[functions.scheduler-trigger]
verify_jwt = false


[functions.speech-to-text]
verify_jwt = false

[functions.fix-tickets-assignment]
verify_jwt = false

[functions.fix-media-keys]
verify_jwt = false
