
project_id = "ymygyagbvbsdfkduxmgu"

[functions.yumer-unified-webhook]
verify_jwt = false

[functions.codechat-webhook]
verify_jwt = false

[functions.codechat-v2-webhook]
verify_jwt = false

[functions.yumer-webhook]
verify_jwt = false
