// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://19c6b746-780c-41f1-97e3-86e1c8f2c488.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IjE5YzZiNzQ2LTc4MGMtNDFmMS05N2UzLTg2ZTFjOGYyYzQ4OCIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzUwNDU0MTY5LCJleHAiOjIwNjYwMzAxNjl9.abc123anonkey";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);